name: Generate Logos

on:
  push:
    tags:
      - "v*"
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y inkscape imagemagick icnsutils
          pip install uv
      - name: Generate logos and montages
        run: |
          uv run ./tools/generate_logos.py -p -i --montage
      - name: Upload logo pngs
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: logos-png
          path: |
            ./logo/generated/*.png
            !./logo/generated/montage.png
      - name: Upload logo svgs
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: logos-svg
          path: |
            ./logo/generated/*.svg
      - name: Upload montage
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: montage
          path: ./logo/generated/montage.png
      - name: Upload icons
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: icons
          path: |
            ./logo/generated/*-plain-*.png
            ./logo/generated/*.ico
            ./logo/generated/*.icns

  release:
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: artifacts
      - name: Archive artifacts
        run: |
          tar vczf logos-svg.tar.gz ./artifacts/logos-svg
          tar vczf logos-png.tar.gz ./artifacts/logos-png
          tar vczf icons.tar.gz ./artifacts/icons
          cp ./artifacts/montage/montage.png .
      - name: Create GitHub release
        uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b # v3.0.1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: |
            ## Logos
            ![Logos montage](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/montage.png)
          files: |
            logos-svg.tar.gz
            logos-png.tar.gz
            icons.tar.gz
            montage.png
